const dummyWorkouts = [
  {
    user: "John Doe",
    date: "2023-01-15",
    workoutName: "Push 1",
    exercises: [
      {
        name: "Bench Press",
        sets: 4,
        reps: [6, 8, 10],
        weight: 75,
        volume: 75 * (6 + 8 + 10),
      },
      {
        name: "Incline Dumbbell Press",
        sets: 3,
        reps: [8, 10],
        weight: 60,
        volume: 60 * (8 + 10),
      },
      {
        name: "Overhead Shoulder Press",
        sets: 3,
        reps: [10, 12],
        weight: 50,
        volume: 50 * (10 + 12),
      },
      {
        name: "Tricep Dips",
        sets: 3,
        reps: [12, 15],
        weight: 55,
        volume: 55 * (12 + 15),
      },
    ],
  },
  {
    user: "Jane Smith",
    date: "2023-02-10",
    workoutName: "Pull 1",
    exercises: [
      {
        name: "Pull-Ups",
        sets: 4,
        reps: [6, 8],
        weight: 70,
        volume: 70 * (6 + 8),
      },
      {
        name: "Barbell Row",
        sets: 3,
        reps: [8, 10, 12],
        weight: 80,
        volume: 80 * (8 + 10 + 12),
      },
      {
        name: "Face Pulls",
        sets: 3,
        reps: [10, 12],
        weight: 45,
        volume: 45 * (10 + 12),
      },
      {
        name: "Bicep Curls",
        sets: 3,
        reps: [12, 15],
        weight: 40,
        volume: 40 * (12 + 15),
      },
    ],
  },
  {
    user: "Alex Johnson",
    date: "2023-03-05",
    workoutName: "Legs 1",
    exercises: [
      {
        name: "Squats",
        sets: 4,
        reps: [8, 10],
        weight: 90,
        volume: 90 * (8 + 10),
      },
      {
        name: "Romanian Deadlifts",
        sets: 3,
        reps: [10, 12],
        weight: 85,
        volume: 85 * (10 + 12),
      },
      {
        name: "Walking Lunges",
        sets: 3,
        reps: [12, 15],
        weight: 50,
        volume: 50 * (12 + 15),
      },
      { name: "Calf Raises", sets: 3, reps: [15], weight: 60, volume: 60 * 15 },
    ],
  },
  {
    user: "John Doe",
    date: "2023-04-20",
    workoutName: "Push 2",
    exercises: [
      {
        name: "Incline Bench Press",
        sets: 4,
        reps: [8, 10],
        weight: 80,
        volume: 80 * (8 + 10),
      },
      {
        name: "Flat Dumbbell Press",
        sets: 3,
        reps: [10, 12],
        weight: 65,
        volume: 65 * (10 + 12),
      },
      {
        name: "Arnold Press",
        sets: 3,
        reps: [12, 15],
        weight: 55,
        volume: 55 * (12 + 15),
      },
      {
        name: "Overhead Tricep Extension",
        sets: 3,
        reps: [15],
        weight: 50,
        volume: 50 * 15,
      },
    ],
  },
  {
    user: "Jane Smith",
    date: "2023-05-18",
    workoutName: "Pull 2",
    exercises: [
      {
        name: "Chin-Ups",
        sets: 4,
        reps: [8, 10],
        weight: 75,
        volume: 75 * (8 + 10),
      },
      {
        name: "T-Bar Row",
        sets: 3,
        reps: [10, 12],
        weight: 85,
        volume: 85 * (10 + 12),
      },
      {
        name: "Rear Delt Flys",
        sets: 3,
        reps: [12, 15],
        weight: 40,
        volume: 40 * (12 + 15),
      },
      {
        name: "Hammer Curls",
        sets: 3,
        reps: [15],
        weight: 45,
        volume: 45 * 15,
      },
    ],
  },
  {
    user: "Alex Johnson",
    date: "2023-06-12",
    workoutName: "Legs 2",
    exercises: [
      {
        name: "Front Squats",
        sets: 4,
        reps: [8, 10],
        weight: 95,
        volume: 95 * (8 + 10),
      },
      {
        name: "Deadlifts",
        sets: 3,
        reps: [10, 12],
        weight: 100,
        volume: 100 * (10 + 12),
      },
      {
        name: "Step-Ups",
        sets: 3,
        reps: [12, 15],
        weight: 55,
        volume: 55 * (12 + 15),
      },
      {
        name: "Seated Calf Raises",
        sets: 3,
        reps: [15],
        weight: 65,
        volume: 65 * 15,
      },
    ],
  },
];

export default dummyWorkouts;
